import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "./ToastProvider"; // client-only component
import AuthGuard from './AuthGuard/AuthGuard'
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div>
            <Providers>
              <AuthGuard>
                {children}
              </AuthGuard>
            </Providers>
          </div>

        {/* Client-only toast container */}
        <ToastProvider />
      </body>
    </html>
  );
}